### ISSUE TITLE
Game value descriptions are partially misleading

### ISSUE THREAD

**Issue by crnvl** [xp-bot/dashboard#50]
![](https://qwq.sh/sqoeyr)

Fish and Loot do not multiply by 1-6, only Roll does.

**Comment by ConnysCode** [comment]
But they do
<img width="463" alt="image" src="https://github.com/xp-bot/dashboard/assets/36863945/3828fde1-18d6-485e-a1c1-9a9f10a32c55">
<img width="463" alt="image" src="https://github.com/xp-bot/dashboard/assets/36863945/28a6f53b-b173-478c-8835-2774e93b0a33">

https://github.com/xp-bot/XP-Discord-Bot/blob/XP-7/src/sets/utils/uGames.ts#L38

**Comment by crnvl** [comment]
chances change in v8, didn't know they did in v7. suggest to change descriptions on release

**Comment by ConnysCode** [comment]
We need specific values to describe the maximum values with. What will the values be in v8? @angelsflyinhell

**Comment by ConnysCode** [comment]
We could also migrate to showing the maximum value which will be divided accordingly in v8.
